version: '3'
services:
  navigation:
    build:
      context: ./navigation
  frontend:
    image: nginx
    ports:
     - "80:80"
    volumes:
    - ./frontend/src:/usr/share/nginx/html
    - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - navigation
      